# Generated by Django 5.1.1 on 2024-09-08 18:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=2000)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=2000)),
                ('entry_time', models.DateTimeField(default=datetime.datetime.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(default=datetime.datetime.now)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.user')),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.user'),
        ),
    ]
