# Generated by Django 5.1.1 on 2024-09-05 13:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_2_split', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='expense',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=2000)),
                ('entry_time', models.DateTimeField(default=datetime.datetime.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(default=datetime.datetime.now)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bill_2_split.payment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
